/**
 * Scheduled task template — used by `nx make:schedule`.
 *
 * Context keys:
 *   name  — PascalCase class name (e.g. "HourlyCleanup")
 *   kebab — kebab-case file name (e.g. "hourly-cleanup")
 */
export default `
import { Injectable } from '@nexusts/core';
import { Cron, Interval, Timeout } from '@nexusts/schedule';

/**
 * {{ name }} task — generated by \`nx make:schedule {{ name }}\`.
 *
 * Mark methods with \`@Cron\`, \`@Interval\`, or \`@Timeout\`.
 * Auto-detected at boot — no manual registration needed.
 */
@Injectable()
export class {{ name }}Task {
  constructor() {}

  // TODO: add @Cron, @Interval, or @Timeout handlers below.

  // @Cron('0 * * * *')                          // every hour
  // async hourly() { /* ... */ }

  // @Interval(60_000)                         // every minute
  // async tick() { /* ... */ }

  // @Timeout(5_000)                            // 5s after boot
  // async startup() { /* ... */ }
}
`.trimStart();
