/**
 * Auth instance template — used by `nx make:auth`.
 *
 * Context keys:
 *   jwt            — boolean, enable JWT plugin
 *   passkey        — boolean, enable passkey (WebAuthn) plugin
 *   passkeyRpName  — string, passkey relying party name
 *   passkeyRpId    — string, passkey relying party ID
 *   passkeyOrigin  — string, passkey origin URL
 *   providers      — boolean, whether social providers are included
 *   entries        — array of { name, envVar } objects
 */
export default `/**
 * Better-auth instance — generated by \`nx make:auth\`.
 *
 * Edit \`nx.config.ts\` (\`auth\` section) instead of this file when possible.
 */
import { createAuth } from '@nexusts/auth';

export const auth = createAuth({
{{^jwt}}
  jwt: { enabled: false },
{{/jwt}}
{{#jwt}}
  jwt: { enabled: true },
{{/jwt}}
{{#passkey}}
  passkey: {
    enabled: true,
    rpName: '{{ passkeyRpName }}',
    rpId:   '{{ passkeyRpId }}',
    origin: '{{ passkeyOrigin }}',
  },
{{/passkey}}
{{#providers}}
  socialProviders: {
{{#entries}}
    {{ name }}: {
      clientId:     process.env.{{ envVar }}_CLIENT_ID!,
      clientSecret: process.env.{{ envVar }}_CLIENT_SECRET!,
    },
{{/entries}}
  },
{{/providers}}
});
`.trimStart();
