/**
 * Auth .env.example template — used by `nx make:auth`.
 *
 * Context keys:
 *   providers  — boolean, whether social providers are included
 *   entries    — array of { name, envVar } objects
 */
export default `# Better Auth — generated by \`nx make:auth\`.
# Generate a secret with: openssl rand -base64 32
BETTER_AUTH_SECRET=
BETTER_AUTH_URL=http://localhost:3000
{{#providers}}
{{#entries}}
{{ envVar }}_CLIENT_ID=
{{ envVar }}_CLIENT_SECRET=
{{/entries}}
{{/providers}}
`.trimStart();
